// Authoritative bank. Import only from server modules, never a client component.
import { primeQuestionSchema, type PrimeQuestion } from "../types";
import type { ConceptId } from "../../learning-signals/types";
const make = (
  id: string,
  concept: ConceptId,
  type: PrimeQuestion["type"],
  prompt: string,
  texts: string[],
  correct: string,
  explanation: string,
  source: "dapa-hf" | "dapa-diabetes" = "dapa-hf",
): PrimeQuestion =>
  primeQuestionSchema.parse({
    id,
    topicId: "heart-failure",
    conceptIds: [concept],
    type,
    prompt,
    options: texts.map((text, i) => ({ id: ["A", "B", "C"][i], text })),
    correctOptionId: correct,
    explanation,
    sourceIds: [source],
    difficulty: "foundation",
    tags: ["DAPA-HF", "evidence interpretation"],
  });
export const questions: PrimeQuestion[] = [
  make(
    "population-1",
    "trial-population",
    "multiple_choice",
    "Who was represented in DAPA-HF?",
    [
      "Only people with diabetes",
      "People with and without diabetes",
      "Only people without diabetes",
    ],
    "B",
    "Diabetes was not an entry requirement; both groups were included.",
    "dapa-diabetes",
  ),
  make(
    "population-2",
    "trial-population",
    "true_false",
    "DAPA-HF required every participant to have diabetes.",
    ["True", "False"],
    "B",
    "The trial included both diabetes groups.",
    "dapa-diabetes",
  ),
  make(
    "population-3",
    "trial-population",
    "multiple_choice",
    "Which ejection-fraction threshold describes the supplied trial population?",
    ["LVEF above 60%", "Every ejection fraction", "LVEF 40% or less"],
    "C",
    "Participants had symptomatic heart failure and LVEF at most 40%.",
  ),
  make(
    "population-4",
    "trial-population",
    "best_supported",
    "Which population claim is best supported?",
    [
      "The trial studied symptomatic HFrEF",
      "The trial studied only healthy volunteers",
      "The trial covered every heart-failure phenotype",
    ],
    "A",
    "The evidence is from symptomatic heart failure with reduced ejection fraction.",
  ),
  make(
    "endpoint-1",
    "primary-endpoint",
    "multiple_choice",
    "What did the primary outcome combine?",
    [
      "Weight and blood pressure",
      "Worsening heart failure and cardiovascular death",
      "Diabetes diagnosis and glucose",
    ],
    "B",
    "The primary outcome was a cardiovascular composite.",
    "dapa-diabetes",
  ),
  make(
    "endpoint-2",
    "primary-endpoint",
    "true_false",
    "The primary outcome was diabetes diagnosis alone.",
    ["True", "False"],
    "B",
    "Worsening heart failure and cardiovascular death formed the primary composite.",
    "dapa-diabetes",
  ),
  make(
    "endpoint-3",
    "primary-endpoint",
    "best_supported",
    "Which comparison did DAPA-HF make?",
    [
      "Dapagliflozin versus placebo alongside usual therapy",
      "Surgery versus exercise alone",
      "No therapy versus emergency treatment",
    ],
    "A",
    "Dapagliflozin and placebo were compared with background therapy.",
  ),
  make(
    "endpoint-4",
    "primary-endpoint",
    "multiple_choice",
    "Which group had fewer primary composite events in the supplied trial summary?",
    ["Both were reported as identical", "Placebo", "Dapagliflozin"],
    "C",
    "The primary composite favored dapagliflozin in the studied population.",
  ),
  make(
    "limits-1",
    "evidence-limitations",
    "true_false",
    "A composite result establishes identical effects on every component.",
    ["True", "False"],
    "B",
    "A combined outcome does not establish equal effects on its parts.",
    "dapa-diabetes",
  ),
  make(
    "limits-2",
    "evidence-limitations",
    "best_supported",
    "How should the diabetes subgroup analysis be understood?",
    [
      "An independent replication",
      "An exploratory analysis of the same trial",
      "A trial of all ejection fractions",
    ],
    "B",
    "These are subgroup findings from DAPA-HF, not a separate replication.",
    "dapa-diabetes",
  ),
  make(
    "limits-3",
    "evidence-limitations",
    "best_supported",
    "Which statement stays within the supplied evidence?",
    [
      "Benefit is guaranteed for each individual",
      "The results replace clinical assessment",
      "Conclusions should retain the trial population's boundaries",
    ],
    "C",
    "Population-level evidence does not determine an individual's treatment.",
  ),
  make(
    "limits-4",
    "evidence-limitations",
    "true_false",
    "DAPA-HF alone establishes benefit at every ejection fraction.",
    ["True", "False"],
    "B",
    "The supplied trial enrolled people with reduced ejection fraction.",
  ),
];
